// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY49uX_KLQ-YyUmYnLI6-Pn31ddCHfhZ4',
    appId: '1:292207782293:web:94314571148be6c3782e9c',
    messagingSenderId: '292207782293',
    projectId: 'attendease-efe98',
    authDomain: 'attendease-efe98.firebaseapp.com',
    storageBucket: 'attendease-efe98.appspot.com',
    measurementId: 'G-6DZJ6J23KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnu9xwbWGG8M5JyTgFIS0-TrUtkCUTcek',
    appId: '1:292207782293:android:09351b706239d71a782e9c',
    messagingSenderId: '292207782293',
    projectId: 'attendease-efe98',
    storageBucket: 'attendease-efe98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_EE9A74_xD1OVVCl6aqaRYr7VB-Pz3pY',
    appId: '1:292207782293:ios:f333df994c788c54782e9c',
    messagingSenderId: '292207782293',
    projectId: 'attendease-efe98',
    storageBucket: 'attendease-efe98.appspot.com',
    iosBundleId: 'com.example.attendease',
  );
}
